# Generated by Django 5.1.6 on 2025-04-25 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicDegree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название учёной степени')),
                ('name_ru', models.CharField(max_length=100, null=True, unique=True, verbose_name='Название учёной степени')),
                ('name_tg', models.CharField(max_length=100, null=True, unique=True, verbose_name='Название учёной степени')),
            ],
            options={
                'verbose_name': 'Научная степень',
                'verbose_name_plural': 'Научные степени',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название преимущества')),
                ('name_ru', models.CharField(max_length=150, null=True, verbose_name='Название преимущества')),
                ('name_tg', models.CharField(max_length=150, null=True, verbose_name='Название преимущества')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_tg', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Пол')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Пол')),
                ('name_tg', models.CharField(max_length=100, null=True, verbose_name='Пол')),
            ],
            options={
                'verbose_name': 'Пол',
                'verbose_name_plural': 'Пол',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Название региона')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Название региона')),
                ('name_tg', models.CharField(max_length=100, null=True, verbose_name='Название региона')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=2, null=True, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Название района')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Название района')),
                ('name_tg', models.CharField(max_length=100, null=True, verbose_name='Название района')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_base.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название подписки')),
                ('name_ru', models.CharField(max_length=150, null=True, verbose_name='Название подписки')),
                ('name_tg', models.CharField(max_length=150, null=True, verbose_name='Название подписки')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_tg', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена в сомони', max_digits=10, verbose_name='Цена')),
                ('duration_days', models.PositiveIntegerField(help_text='Сколько дней действует подписка после активации', verbose_name='Длительность (дней)')),
                ('is_active', models.BooleanField(default=True, help_text='Доступна ли подписка для покупки', verbose_name='Активна')),
                ('advantages', models.ManyToManyField(blank=True, related_name='subscriptions', to='a_base.advantage', verbose_name='Преимущества')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'ordering': ['name'],
            },
        ),
    ]
