# Generated by Django 5.1.6 on 2025-04-23 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название области (например, Согдийская область)', max_length=100, verbose_name='Название области')),
                ('name_ru', models.CharField(help_text='Название области (например, Согдийская область)', max_length=100, null=True, verbose_name='Название области')),
                ('name_tg', models.CharField(help_text='Название области (например, Согдийская область)', max_length=100, null=True, verbose_name='Название области')),
            ],
            options={
                'verbose_name': 'Область',
                'verbose_name_plural': 'Области',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название города или района (например, Душанбе)', max_length=100, verbose_name='Название города/района')),
                ('name_ru', models.CharField(help_text='Название города или района (например, Душанбе)', max_length=100, null=True, verbose_name='Название города/района')),
                ('name_tg', models.CharField(help_text='Название города или района (например, Душанбе)', max_length=100, null=True, verbose_name='Название города/района')),
                ('region', models.ForeignKey(help_text='Область, к которой принадлежит город/район', on_delete=django.db.models.deletion.CASCADE, to='a_base.region', verbose_name='Область')),
            ],
            options={
                'verbose_name': 'Город/Район',
                'verbose_name_plural': 'Города/Районы',
                'ordering': ['name'],
            },
        ),
    ]
