# Generated by Django 5.1.6 on 2025-04-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(help_text='Диапазон лет опыта работы', max_length=50, unique=True, verbose_name='Уровень опыта')),
                ('level_ru', models.CharField(help_text='Диапазон лет опыта работы', max_length=50, null=True, unique=True, verbose_name='Уровень опыта')),
                ('level_tg', models.CharField(help_text='Диапазон лет опыта работы', max_length=50, null=True, unique=True, verbose_name='Уровень опыта')),
            ],
            options={
                'verbose_name': 'Уровень опыта',
                'verbose_name_plural': 'Уровни опыта',
                'ordering': ['level'],
            },
        ),
    ]
