# Generated by Django 5.1.6 on 2025-04-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название специальности')),
                ('name_ru', models.CharField(max_length=255, null=True, unique=True, verbose_name='Название специальности')),
                ('name_tg', models.CharField(max_length=255, null=True, unique=True, verbose_name='Название специальности')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
            },
        ),
    ]
