# Generated by Django 5.1.6 on 2025-04-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['name'], 'verbose_name': 'Район', 'verbose_name_plural': 'Районы'},
        ),
        migrations.AlterField(
            model_name='district',
            name='code',
            field=models.CharField(blank=True, max_length=2, null=True, unique=True),
        ),
    ]
