# Generated by Django 5.1.6 on 2025-05-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название статуса')),
                ('name_ru', models.CharField(max_length=255, null=True, unique=True, verbose_name='Название статуса')),
                ('name_tg', models.CharField(max_length=255, null=True, unique=True, verbose_name='Название статуса')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='CancelReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название причины отмены записи')),
            ],
            options={
                'verbose_name': 'Причина отмены записи',
                'verbose_name_plural': 'Причины отмены записи',
            },
        ),
    ]
