# Generated by Django 5.1.6 on 2025-05-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_base', '0002_appointmentstatus_cancelreason'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelreason',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Название причины отмены записи'),
        ),
        migrations.AddField(
            model_name='cancelreason',
            name='name_tg',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Название причины отмены записи'),
        ),
    ]
