# Generated by Django 5.1.6 on 2025-04-23 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_base', '0002_alter_district_options_alter_district_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['name'], 'verbose_name': 'Регион', 'verbose_name_plural': 'Регионы'},
        ),
    ]
