# Generated by Django 5.1.6 on 2025-04-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_base', '0002_experiencelevel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gender',
            options={'ordering': ['name'], 'verbose_name': 'Пол (мужской, женский)', 'verbose_name_plural': 'Полы (мужской, женский)'},
        ),
        migrations.AlterField(
            model_name='gender',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название пола (мужской, женский)'),
        ),
        migrations.AlterField(
            model_name='gender',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название пола (мужской, женский)'),
        ),
        migrations.AlterField(
            model_name='gender',
            name='name_tg',
            field=models.CharField(max_length=100, null=True, verbose_name='Название пола (мужской, женский)'),
        ),
    ]
