# Generated by Django 5.1.6 on 2025-04-29 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_base', '0002_medicalcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Место предоставляемой услуги')),
                ('name_ru', models.CharField(max_length=255, null=True, unique=True, verbose_name='Место предоставляемой услуги')),
                ('name_tg', models.CharField(max_length=255, null=True, unique=True, verbose_name='Место предоставляемой услуги')),
            ],
            options={
                'verbose_name': 'Место предоставляемой услуги',
                'verbose_name_plural': 'Места предоставляемых услуг',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название услуги')),
                ('name_ru', models.CharField(max_length=255, null=True, unique=True, verbose_name='Название услуги')),
                ('name_tg', models.CharField(max_length=255, null=True, unique=True, verbose_name='Название услуги')),
                ('description', models.TextField(blank=True, verbose_name='Описание услуги')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание услуги')),
                ('description_tg', models.TextField(blank=True, null=True, verbose_name='Описание услуги')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('service_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_base.serviceplace', verbose_name='Место предоставляемой услуги')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
