# Generated by Django 5.1.6 on 2025-04-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_base', '0003_serviceplace_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название услуги'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название услуги'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name_tg',
            field=models.CharField(max_length=255, null=True, verbose_name='Название услуги'),
        ),
    ]
