# Generated by Django 5.1.6 on 2025-05-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_base', '0003_alter_gender_options_alter_gender_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Название социального статуса (например, 'Студент', 'Пенсионер').", max_length=50, unique=True, verbose_name='Название')),
                ('name_ru', models.CharField(help_text="Название социального статуса (например, 'Студент', 'Пенсионер').", max_length=50, null=True, unique=True, verbose_name='Название')),
                ('name_tg', models.CharField(help_text="Название социального статуса (например, 'Студент', 'Пенсионер').", max_length=50, null=True, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, help_text='Краткое описание социального статуса.', null=True, verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, help_text='Краткое описание социального статуса.', null=True, verbose_name='Описание')),
                ('description_tg', models.TextField(blank=True, help_text='Краткое описание социального статуса.', null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Социальный статус',
                'verbose_name_plural': 'Социальные статусы',
            },
        ),
    ]
