# Generated by Django 5.1.6 on 2025-05-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_base', '0003_cancelreason_name_ru_cancelreason_name_tg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointmentstatus',
            options={'verbose_name': 'Статус записи', 'verbose_name_plural': 'Статусы записей'},
        ),
        migrations.AlterField(
            model_name='appointmentstatus',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название статуса записи'),
        ),
        migrations.AlterField(
            model_name='appointmentstatus',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Название статуса записи'),
        ),
        migrations.AlterField(
            model_name='appointmentstatus',
            name='name_tg',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Название статуса записи'),
        ),
    ]
