# Generated by Django 5.1.6 on 2025-04-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_base', '0003_alter_region_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicDegree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название учёной степени')),
            ],
            options={
                'verbose_name': 'Научная степень',
                'verbose_name_plural': 'Научные степени',
                'ordering': ['name'],
            },
        ),
    ]
