# Generated by Django 5.1.6 on 2025-04-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_base', '0004_academicdegree'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicdegree',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Название учёной степени'),
        ),
        migrations.AddField(
            model_name='academicdegree',
            name='name_tg',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Название учёной степени'),
        ),
    ]
