# Generated by Django 5.1.6 on 2025-04-26 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_base', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.ForeignKey(blank=True, help_text='Пол пользователя', null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_base.gender'),
        ),
    ]
