# Generated by Django 5.1.6 on 2025-04-26 13:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('a_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название типа клиники')),
                ('name_ru', models.CharField(max_length=255, null=True, unique=True, verbose_name='Название типа клиники')),
                ('name_tg', models.CharField(max_length=255, null=True, unique=True, verbose_name='Название типа клиники')),
            ],
            options={
                'verbose_name': 'Тип клиники',
                'verbose_name_plural': 'Типы клиник',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Официальное название клиники', max_length=255, verbose_name='Название клиники')),
                ('name_ru', models.CharField(help_text='Официальное название клиники', max_length=255, null=True, verbose_name='Название клиники')),
                ('name_tg', models.CharField(help_text='Официальное название клиники', max_length=255, null=True, verbose_name='Название клиники')),
                ('address', models.CharField(help_text='Адрес клиники', max_length=255, verbose_name='Адрес')),
                ('address_ru', models.CharField(help_text='Адрес клиники', max_length=255, null=True, verbose_name='Адрес')),
                ('address_tg', models.CharField(help_text='Адрес клиники', max_length=255, null=True, verbose_name='Адрес')),
                ('country', models.CharField(default='Таджикистан', help_text='Страна, где находится клиника', max_length=100, verbose_name='Страна')),
                ('phone_number', models.CharField(blank=True, help_text='Контактный номер клиники', max_length=13, null=True, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+992XXYYYYYY'.", regex='^\\+992\\d{9}$')], verbose_name='Контактный телефон')),
                ('email', models.EmailField(blank=True, help_text='Электронная почта клиники', max_length=254, null=True, verbose_name='Электронная почта')),
                ('website', models.URLField(blank=True, help_text='Официальный веб-сайт клиники', null=True, verbose_name='Веб-сайт')),
                ('latitude', models.FloatField(blank=True, help_text='Географическая широта местоположения клиники', null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, help_text='Географическая долгота местоположения клиники', null=True, verbose_name='Долгота')),
                ('district', models.ForeignKey(help_text='Район, где находится клиника', on_delete=django.db.models.deletion.CASCADE, to='a_base.district', verbose_name='Район')),
                ('clinic_type', models.ForeignKey(help_text='Тип клиники (Госпитальная служба или Учреждение ПМСП)', on_delete=django.db.models.deletion.PROTECT, to='clinics.clinictype', verbose_name='Тип клиники')),
            ],
            options={
                'verbose_name': 'Клиника',
                'verbose_name_plural': 'Клиники',
                'ordering': ['name'],
            },
        ),
    ]
