# Generated by Django 5.1.6 on 2025-04-25 13:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(help_text='Дата на которую назначен прием', verbose_name='Дата приема')),
                ('start_time', models.TimeField(help_text='Планируемое время начала приема', verbose_name='Время начала')),
                ('end_time', models.TimeField(help_text='Планируемое время окончания приема', verbose_name='Время окончания')),
                ('status', models.CharField(choices=[('complete', 'Завершен'), ('upcoming', 'Предстоящий'), ('cancelled', 'Отменен'), ('noshow', 'Пациент не явился')], default='upcoming', max_length=10, verbose_name='Статус приема')),
                ('cancellation_reason', models.CharField(blank=True, choices=[('rescheduling', 'Перенос приема'), ('weather', 'Погодные условия'), ('work', 'Неожиданные рабочие обстоятельства'), ('personal', 'Личные причины'), ('health', 'Проблемы со здоровьем'), ('others', 'Другое')], max_length=20, null=True, verbose_name='Причина отмены')),
                ('cancellation_notes', models.TextField(blank=True, max_length=500, null=True, verbose_name='Комментарий при отмене')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Время отмены')),
                ('phone_number', models.CharField(help_text='Контактный номер пациента', max_length=13, validators=[django.core.validators.RegexValidator(message="Формат номера: '+992XXYYYYYY'.", regex='^\\+992\\d{9}$')], verbose_name='Телефон')),
                ('is_another_patient', models.BooleanField(default=False, verbose_name='Запись для другого человека')),
                ('another_patient_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО другого пациента')),
                ('another_patient_age', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)], verbose_name='Возраст')),
                ('another_patient_gender', models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский'), ('other', 'Другое')], max_length=10, null=True, verbose_name='Пол')),
                ('problem_description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Описание проблемы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Запись на прием',
                'verbose_name_plural': 'Записи на прием',
                'ordering': ['appointment_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 - Очень плохо'), (2, '2 - Плохо'), (3, '3 - Удовлетворительно'), (4, '4 - Хорошо'), (5, '5 - Отлично')], help_text='Оценка от 1 до 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('comment', models.TextField(blank=True, help_text='Текст отзыва (максимум 2000 символов)', max_length=2000, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания отзыва', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления отзыва', verbose_name='Дата обновления')),
                ('is_published', models.BooleanField(default=True, help_text='Показывать ли отзыв на сайте', verbose_name='Опубликован')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
    ]
