# Generated by Django 5.1.6 on 2025-04-23 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='doctors.doctor', verbose_name='Врач'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='patients.patient', verbose_name='Пациент'),
        ),
        migrations.AddField(
            model_name='review',
            name='appointment',
            field=models.OneToOneField(help_text='Запись на прием, к которой относится отзыв', on_delete=django.db.models.deletion.CASCADE, related_name='review', to='appointments.appointment', verbose_name='Запись на прием'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('doctor', 'appointment_date', 'start_time'), name='unique_doctor_time_slot'),
        ),
    ]
