# Generated by Django 5.1.6 on 2025-05-07 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_base', '0002_appointmentstatus_cancelreason'),
        ('appointments', '0002_initial'),
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='another_patient_gender',
            field=models.ForeignKey(blank=True, help_text='Пол пациента, который записывается на прием', null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_base.gender', verbose_name='Пол пациента'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='cancellation_reason',
            field=models.ForeignKey(blank=True, help_text='Причина отмены приема пациентом', null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_base.cancelreason', verbose_name='Причина отмены приема'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='doctors.doctor', verbose_name='Врач'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient', verbose_name='Пациент'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.ForeignKey(help_text='Статус приема', on_delete=django.db.models.deletion.CASCADE, to='a_base.appointmentstatus', verbose_name='Статус приема'),
        ),
    ]
