# Generated by Django 5.1.6 on 2025-03-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название преимущества')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название подписки')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена в сомони', max_digits=10, verbose_name='Цена')),
                ('duration_days', models.PositiveIntegerField(help_text='Сколько дней действует подписка после активации', verbose_name='Длительность (дней)')),
                ('is_active', models.BooleanField(default=True, help_text='Доступна ли подписка для покупки', verbose_name='Активна')),
                ('advantages', models.ManyToManyField(blank=True, related_name='subscriptions', to='subscriptions.advantage', verbose_name='Преимущества')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'ordering': ['price'],
            },
        ),
    ]
