import random
from datetime import time
from faker import Faker
from django.core.management.base import BaseCommand
from doctors.models import MedicalInstitution, Workplace, Doctor, Schedule
from a_base.models import City, Region

fake = Faker()

class Command(BaseCommand):
    help = 'Заполняет базу объектами медицинских учреждений, а также местами работы врачей и их расписанием.'

    def handle(self, *args, **kwargs):

        # Создание тестовых данных для медицинских учреждений
        self.stdout.write("Создание тестовых данных для медицинских учреждений...")
        medical_institutions_data = [
            # Душанбе
            {
                "institution_type": "HOSPITAL",
                "name": "МД “Маркази милли бемориҳои сил, шуш ва ҷарроҳии қафаси сина”",
                "address": "ш.Ваҳдат, ҷамоати Баҳор, деҳаи Мачитон",
                "city": "Вахдат",
                "region": "Душанбе",
            },
            {
                "institution_type": "HOSPITAL",
                "name": "МД “МТ Истиқлол”",
                "address": "хиёбони Н. Қарабоев 54/1 (нишонӣ: Султони Кабир)",
                "city": "Душанбе",
                "region": "Душанбе",
            },
            {
                "institution_type": "HOSPITAL",
                "name": "Маркази милли тибби “Шифобахш”",
                "address": "хиёбони И. Сомонӣ 59 (нишонӣ: Қарияи Боло)",
                "city": "Душанбе",
                "region": "Душанбе",
            },
            {
                "institution_type": "HOSPITAL",
                "name": "МД “Маркази ҷумҳуриявии илмии ҷарроҳии дилу рагҳо”",
                "address": "кӯч. Саноӣ 33 (нишонӣ: Медгородок)",
                "city": "Душанбе",
                "region": "Душанбе",
            },
            {
                "institution_type": "HOSPITAL",
                "name": "МД “МТШ №1 ба номи Ахмедов Карим” (медгородок)",
                "address": "кӯч. Абай 3 (нишонӣ: 1-ум Советский)",
                "city": "Душанбе",
                "region": "Душанбе",
            },
            {
                "institution_type": "HOSPITAL",
                "name": "МД “МТШ №2”",
                "address": "кӯч. Саноӣ 33 (нишонӣ: Медгородок)",
                "city": "Душанбе",
                "region": "Душанбе",
            },
            {
                "institution_type": "HOSPITAL",
                "name": "МД “МТШ №3”",
                "address": "кӯч. Ак. Раҷабовҳо 6/2 (нишонӣ: Вазорати адлия)",
                "city": "Душанбе",
                "region": "Душанбе",
            },
            {
                "institution_type": "HOSPITAL",
                "name": "МД “Таваллудхонаи шаҳрии №1”",
                "address": "хиёбони Н. Махсум 93 (нишонӣ: 102-юм мкр)",
                "city": "Душанбе",
                "region": "Душанбе",
            },
            {
                "institution_type": "HOSPITAL",
                "name": "МД “Таваллудхонаи шаҳрии №2”",
                "address": "кӯч. Ш. Ҳусейнзода 5 (нишонӣ: горздрав)",
                "city": "Душанбе",
                "region": "Душанбе",
            },
            {
                "institution_type": "HOSPITAL",
                "name": "МД “Беморхонаи клиникии шаҳрии бемориҳои сироятӣ”",
                "address": "кӯч. Зарафшон 2М11 (нишонӣ: Зарнисор)",
                "city": "Душанбе",
                "region": "Душанбе",
            },
            {
                "institution_type": "HOSPITAL",
                "name": "МД “Беморхонаи клиникии шаҳрии бемориҳои сироятии кӯдакона”",
                "address": "хиёбони Н. Қарабоев 54/1 (нишонӣ: Беморх. Истиқлол)",
                "city": "Душанбе",
                "region": "Душанбе",
            },
            {
                "institution_type": "HOSPITAL",
                "name": "МД “Маркази шаҳрии ёрии таъҷилии тиббӣ”",
                "address": "кӯч. Айнӣ 46 (нишонӣ: Созидание)",
                "city": "Душанбе",
                "region": "Душанбе",
            },
            {
                "institution_type": "HOSPITAL",
                "name": "МД “Беморхонаи клиникии шаҳрии бемориҳои пӯст”",
                "address": "кӯч. Хатлон 4 (нишонӣ: Мясокомбинат)",
                "city": "Душанбе",
                "region": "Душанбе",
            },
            {
                "institution_type": "HOSPITAL",
                "name": "МД “Беморхонаи шаҳрии кӯдаконаи бемориҳои сил”",
                "address": "кӯч. Азизбеков 45 (нишонӣ: Театри лӯхтак)",
                "city": "Душанбе",
                "region": "Душанбе",
            },
            {
                "institution_type": "HOSPITAL",
                "name": "МД “Шифохонаи парастории ҳамшираҳои шафқат”",
                "address": "кӯч. Фирдавсӣ 28 (нишонӣ: 63-юм мкр-Саховат)",
                "city": "Душанбе",
                "region": "Душанбе",
            },
            {
                "institution_type": "HOSPITAL",
                "name": "МД “Маркази шаҳрии бемориҳои пӯст ва зуҳравӣ”",
                "address": "кӯч. Р. Набиев 29 (нишонӣ: Яккачинор)",
                "city": "Душанбе",
                "region": "Душанбе",
            },
            {
                "institution_type": "HOSPITAL",
                "name": "МД “Маркази шаҳрии илмии реаниматсия ва детоксикатсия”",
                "address": "кӯч. Саноӣ 33 (нишонӣ: Шаҳраки тиббӣ)",
                "city": "Душанбе",
                "region": "Душанбе",
            },
            {
                "institution_type": "HOSPITAL",
                "name": "Маркази худмаблағгузори колопроктологӣ",
                "address": "кӯч. Саноӣ 33 (нишонӣ: Шаҳраки тиббӣ)",
                "city": "Душанбе",
                "region": "Душанбе",
            },
            {
                "institution_type": "HOSPITAL",
                "name": "МД “Маркази ҷумҳуриявии илмии саратоншиносӣ”",
                "address": "хиёбони И. Сомонӣ 59 (нишонӣ: Қарияи Боло)",
                "city": "Душанбе",
                "region": "Душанбе",
            },
            {
                "institution_type": "HOSPITAL",
                "name": "КВД “Маркази миллии ташхису табобат ва таълимӣ”",
                "address": "кӯч. Деҳотӣ 48 (нишонӣ: Султони Кабир)",
                "city": "Душанбе",
                "region": "Душанбе",
            },
            {
                "institution_type": "HOSPITAL",
                "name": "МД “Маркази миллии илмии пайвандсозии узв ва бофтаҳои инсон”",
                "address": "хиёбони Н. Қарабоев 54/1 (нишонӣ: Беморх. Истиқлол Бинои 6)",
                "city": "Душанбе",
                "region": "Душанбе",
            },
            {
                "institution_type": "HOSPITAL",
                "name": "МД “Пажӯҳишгоҳи акушерӣ, гинекологӣ ва перинатологии Тоҷикистон”",
                "address": "кӯч. М. Турсунзода 29 (нишонӣ: Донишгоҳи славянӣ)",
                "city": "Душанбе",
                "region": "Душанбе",
            },
            {
                "institution_type": "HOSPITAL",
                "name": "МД “Пажӯҳишгоҳи гастроэнтерологияи Ҷумҳурии Тоҷикистон”",
                "address": "Кӯч. Маяковский 2 (нишонӣ: Сафоратхонаи Олмон)",
                "city": "Душанбе",
                "region": "Душанбе",
            },
            {
                "institution_type": "HOSPITAL",
                "name": "МД “Пажӯҳишгоҳи илмию клиникии стоматология ва ҷарроҳии ҷоғу рӯй”",
                "address": "кӯч. Хуҷандӣ 13 (нишонӣ: Беморх. 1-ум Советский)",
                "city": "Душанбе",
                "region": "Душанбе",
            },
            {
                "institution_type": "HOSPITAL",
                "name": "МД “Маркази ҷумҳуриявии клиникии бемориҳои пӯст ва узвҳои таносул”",
                "address": "ш. Душанбе, 2-юм гузарг. кӯч. Айнӣ 52 (нишонӣ: ДОК-Жилмассив)",
                "city": "Душанбе",
                "region": "Душанбе",
            },
            {
                "institution_type": "HOSPITAL",
                "name": "МД “Маркази ҷумҳуриявии клиникии бемориҳои дил”",
                "address": "хиёбони И. Сомонӣ 59 (нишонӣ: Қарияи Боло)",
                "city": "Душанбе",
                "region": "Душанбе",
            },
            {
                "institution_type": "HOSPITAL",
                "name": "МД “Маркази ҷумҳуриявии илмию клиникии урологӣ”",
                "address": "хиёбони И. Сомонӣ 59 (нишонӣ: Қарияи Боло)",
                "city": "Душанбе",
                "region": "Душанбе",
            },
            {
                "institution_type": "HOSPITAL",
                "name": "КВД “Маркази ҷумҳуриявии клиникии бемориҳои сутунмӯҳра”",
                "address": "КВД “Маркази ҷумҳуриявии клиникии бемориҳои сутунмӯҳра”",
                "city": "Душанбе",
                "region": "Душанбе",
            },
            # Хатлонская область
            {
                "institution_type": "HOSPITAL",
                "name": "Беморхонаи клиникии ба номи Б.Воњидов –и вилояти Хатлон",
                "address": "н. Кӯшониён, беморхонаи Қараболо",
                "city": "Кушониён",
                "region": "Хатлонская область",
            },
            {
                "institution_type": "HOSPITAL",
                "name": "Беморхонаи вилоятии ба номи А. Хакназаров",
                "address": "ш. Кулоб, махаллаи Борбад 38",
                "city": "Куляб",
                "region": "Хатлонская область",
            },
            {
                "institution_type": "HOSPITAL",
                "name": "Беморхонаи Марказии нохияви",
                "address": "Восеъ, кучаи ",
                "city": "Восеъ",
                "region": "Хатлонская область",
            },
            {
                "institution_type": "HOSPITAL",
                "name": "Беморхонаи Марказии нохиявии Дангара",
                "address": "Дангара, кучаи",
                "city": "Дангара",
                "region": "Хатлонская область",
            },
            # Согдийская область
            {
                "institution_type": "HOSPITAL",
                "name": "Беморхонаи клиникавии вилояти Суғд ба номи С.Қутфиддинов",
                "address": "Минтақаи шимолу шарқӣ микроноҳияи 34",
                "city": "Худжанд",
                "region": "Согдийская область",
            },
            {
                "institution_type": "HOSPITAL",
                "name": "БКШ №1 ба номи Султон Ӯрунов",
                "address": "ул.Ю.Гагарина 147А",
                "city": "Худжанд",
                "region": "Согдийская область",
            },
            {
                "institution_type": "HOSPITAL",
                "name": "Беморхонаи шаҳрии №2",
                "address": "куч.Варзишгарон 12А",
                "city": "Худжанд",
                "region": "Согдийская область",
            },
            {
                "institution_type": "HOSPITAL",
                "name": "Таваллудхонаи вилояти Суғд ба номи Ӯғулой Шамсиддинова",
                "address": "Кучаи Раҳмон Набиев",
                "city": "Худжанд",
                "region": "Согдийская область",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "КАТС и ш. Бохтар",
                "address": "ш. Бохтар. Кӯчаи С.Айни 88",
                "city": "Бохтар",
                "region": "Хатлонская область",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "КАТС и н. Ёвон",
                "address": "Шаҳраки Ёвон, кӯчаи А. Ҷомӣ 1",
                "city": "Ёвон",
                "region": "Хатлонская область",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "КАТС и ноҳия А. Ҷомӣ",
                "address": "Шаҳраки А. Ҷомӣ, кучаи И. Сомониен 1",
                "city": "А. Ҷомӣ",
                "region": "Хатлонская область",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "КАТС и ноҳия Хуросон",
                "address": "ч/д шахраки Обикиик",
                "city": "Хуросон",
                "region": "Хатлонская область",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "КАТС и ноҳия Левакант",
                "address": "Шаҳраки Леваканд, кучаи Н. Абдулло 31",
                "city": "Левакант",
                "region": "Хатлонская область",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "КАТС и ноҳия Кўшониён",
                "address": "Шаҳраки И. Сомонӣ, кӯчаи Сино 2",
                "city": "Кўшониён",
                "region": "Хатлонская область",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "КАТС и ноҳия Вахш",
                "address": "",
                "city": "Вахш",
                "region": "Хатлонская область",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "КАТС и ноҳия Норак",
                "address": "Шаҳри Норак, кӯчаи А. Ҷомӣ 1",
                "city": "Норак",
                "region": "Хатлонская область",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "КАТС и ноҳия Дустӣ",
                "address": "Шаҳраки кӯчаи А. Каримов 12",
                "city": "Дустӣ",
                "region": "Хатлонская область",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "КАТС и ноҳия Ҷ. Балхӣ",
                "address": "Шаҳраки Балхӣ, кӯчаи Сино 1",
                "city": "Ҷ. Балхӣ",
                "region": "Хатлонская область",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "КАТС и ноҳия Ҷайҳун",
                "address": "Шаҳраки Ҷайҳун, кӯчаи",
                "city": "Ҷайҳун",
                "region": "Хатлонская область",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "КАТС и ноҳия Панҷ",
                "address": "Шаҳраки Панҷ, кӯчаи Рудаки 57",
                "city": "Панҷ",
                "region": "Хатлонская область",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "КАТС и ноҳия Қубодиён",
                "address": "Шаҳраки Қубодиён, кӯчаи Н.Хусрав 1",
                "city": "Қубодиён",
                "region": "Хатлонская область",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "КАТС и ноҳия Шаҳритуз",
                "address": "Ш. Шахритус, кӯчаи И. Сомони 78",
                "city": "Шаҳритуз",
                "region": "Хатлонская область",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "КАТС и ноҳия Н. Хусрав",
                "address": "ч/д Фируза, шаҳраки Бахор 1",
                "city": "Н. Хусрав",
                "region": "Хатлонская область",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "КАТС и ш. Кӯлоб",
                "address": "кӯчаи И. Сомонӣ №42",
                "city": "Кӯлоб",
                "region": "Хатлонская область",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "КАТС и ноҳия Кӯлоб",
                "address": "ҷ/д Зираки маҳалаи зарқалъа",
                "city": "Кӯлоб",
                "region": "Хатлонская область",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "КАТС и ноҳия Восеъ",
                "address": "н. Восе кӯчаи Абдувалӣ Мирзоев №1",
                "city": "Восеъ",
                "region": "Хатлонская область",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "КАТС и ноҳия Данғара",
                "address": "Шаҳри Данғара, маҳ. Киров 35",
                "city": "Данғара",
                "region": "Хатлонская область",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "КАТС и ноҳия М. Ҳамадонӣ",
                "address": "шаҳраки Москва, кӯчаи Б. Гафуров 33",
                "city": "М. Ҳамадонӣ",
                "region": "Хатлонская область",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "КАТС и ноҳия Фархор",
                "address": "н. Ҳамадонӣ кӯчаи Б. Ғафуров №31",
                "city": "Фархор",
                "region": "Хатлонская область",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "КАТС и ноҳия Ховалинг",
                "address": "Ҷам.шаҳраки Ховалинг маҳ.С.Вализода 66",
                "city": "Ховалинг",
                "region": "Хатлонская область",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "КАТС и ноҳия Муъминобод",
                "address": "кӯчаи Темуршоҳ Раҳимов №15",
                "city": "Муъминобод",
                "region": "Хатлонская область",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "КАТС и ноҳия Ш.Шоҳин",
                "address": "ҷ/д Навобод",
                "city": "Ш.Шоҳин",
                "region": "Хатлонская область",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "КАТС и ноҳия Балҷувон",
                "address": "ҷам. Балҷувон, деҳ. Балҷувон",
                "city": "Балҷувон",
                "region": "Хатлонская область",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "КАТС и ноҳия Темурмалик",
                "address": "ҷам. Баҳмаруб, маҳ. Абуалӣ ибни Сино 3",
                "city": "Темурмалик",
                "region": "Хатлонская область",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "КАТС",
                "address": "кучаи Айни дехаи Айни №1",
                "city": "Айнӣ",
                "region": "Согдийская область",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "КАТС",
                "address": "шахраки Гончи кучаи Сино 8",
                "city": "Деваштич",
                "region": "Согдийская область",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "КАТС",
                "address": "ш.Исторавшан кучаи Истиклол 168",
                "city": "Истаравшан",
                "region": "Согдийская область",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "КАТС",
                "address": "Дехаи Ревомот",
                "city": "Кӯҳистони Мастчоҳ",
                "region": "Согдийская область",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "КАТС",
                "address": "кучаи 50 солаги Точикистон бинои 6",
                "city": "Панҷакент",
                "region": "Согдийская область",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "КАТС",
                "address": "дехаи Шахристон кучаи Сино 8",
                "city": "Шаҳристон",
                "region": "Согдийская область",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "КАТС",
                "address": "шахраки Навкат кучаи Спитамен 46",
                "city": "Спитамен",
                "region": "Согдийская область",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "КАТС",
                "address": "шахраки Зафороб кучаи Чура Зарипов 2",
                "city": "Зафоробод",
                "region": "Согдийская область",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "шабакаи муассисахои КАТС",
                "address": "шаҳраки Шайдон к.И.Сомони 67",
                "city": "Ашт",
                "region": "Согдийская область",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "МСН",
                "address": "шаҳраки Шайдон к.И.Сомони 67",
                "city": "Ашт",
                "region": "Согдийская область",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "шабакаи муассисахои КАТС",
                "address": "ҷамоати шаҳраки Бустон к О.Курбон 65/5",
                "city": "Мастчоҳ",
                "region": "Согдийская область",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "МСН",
                "address": "ҷамоати шаҳраки Бустон к О.Курбон 65/5",
                "city": "Мастчоҳ",
                "region": "Согдийская область",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "КАТС",
                "address": "ш.Бустон к.А.Сино 6",
                "city": "Бустон",
                "region": "Согдийская область",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "МСШ",
                "address": "ш.Бустон к.А.Сино 6",
                "city": "Бустон",
                "region": "Согдийская область",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "шабакаи муассисахои КАТС",
                "address": "ш.Гулистон к.Истиклол 70",
                "city": "Гулистон",
                "region": "Согдийская область",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "МСШ",
                "address": "ш.Гулистон к.Истиклол 70",
                "city": "Гулистон",
                "region": "Согдийская область",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "шабакаи муассисахои КАТС",
                "address": "ш.Истиклол к.И.Сомонӣ 41",
                "city": "Истиқлол",
                "region": "Согдийская область",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "МСШ",
                "address": "ш.Истиклол к.И.Сомонӣ 41",
                "city": "Истиқлол",
                "region": "Согдийская область",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "шабакаи муассисахои КАТС",
                "address": "ш.Конибодом к.8 март 56",
                "city": "Конибодом",
                "region": "Согдийская область",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "МСШ №1",
                "address": "ш.Конибодом к.8 март 56",
                "city": "Конибодом",
                "region": "Согдийская область",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "МСШ №2",
                "address": "ш.Конибодом к.8 март 56",
                "city": "Конибодом",
                "region": "Согдийская область",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "МСШ №1",
                "address": "ш.Хуҷанд, кучаи Мақсудҷон Танбурӣ 35",
                "city": "Хучанд",
                "region": "Согдийская область",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "МСШ №2",
                "address": "ш.Хуҷанд, кучаи Камоли Хуҷандӣ 181",
                "city": "Хучанд",
                "region": "Согдийская область",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "МСШ №3",
                "address": "ш.Хуҷанд, кучаи Баҳор 1 а",
                "city": "Хучанд",
                "region": "Согдийская область",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "МСШ №4",
                "address": "ш.Хуҷанд, кучаи Дустии халқҳо",
                "city": "Хучанд",
                "region": "Согдийская область",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "МСШ №5",
                "address": "ш.Хуҷанд, микроноҳияи 18",
                "city": "Хучанд",
                "region": "Согдийская область",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "МСШ №6",
                "address": "ш.Хуҷанд, к.Варзишгарон 12 а",
                "city": "Хучанд",
                "region": "Согдийская область",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "КАТС",
                "address": "",
                "city": "Ҷабор Расулов",
                "region": "Согдийская область",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "КАТС",
                "address": "",
                "city": "Исфара",
                "region": "Согдийская область",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "КАТС",
                "address": "",
                "city": "Бобоҷон Ғаффуров",
                "region": "Согдийская область",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "МСШ №1",
                "address": "ш. Душанбе, кӯч. Фирдавсӣ 13/2 (Зебошка)",
                "city": "Фирдавсӣ",
                "region": "Душанбе",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "МСШ №2",
                "address": "ш. Душанбе, кӯч. Раҳимӣ 1 (пушти Прокуратураи генералӣ)",
                "city": "Сино",
                "region": "Душанбе",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "МСШ №3",
                "address": "ш. Душанбе, кӯч. Айнӣ 80 (ДОК, 7-ум километр)",
                "city": "Шоҳмансур",
                "region": "Душанбе",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "МСШ №4",
                "address": "ш. Душанбе, кӯч. Деҳотӣ 9/5 (пушти Донишкадаи Тиҷорат)",
                "city": "Фирдавсӣ",
                "region": "Душанбе",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "МСШ №5",
                "address": "ш. Душанбе, кӯч. Аҳмади Дониш 12 (назди Фурӯдгоҳ)",
                "city": "Шоҳмансур",
                "region": "Душанбе",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "МСШ №6",
                "address": "ш. Душанбе, кӯч. Абулқосим Лоҳутӣ 63 (Пивзавод)",
                "city": "И. Сомонӣ",
                "region": "Душанбе",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "МСШ №7",
                "address": "ш. Душанбе, кӯч. Абай 3 (1-ум Советский)",
                "city": "Сино",
                "region": "Душанбе",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "МСШ №8",
                "address": "ш. Душанбе, кӯч. Рӯдакӣ 186 (парки С.Айнӣ)",
                "city": "И. Сомонӣ",
                "region": "Душанбе",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "МСШ №9",
                "address": "ш. Душанбе, кӯч. Шамсӣ 5А (назди Мелиоратсия)",
                "city": "Сино",
                "region": "Душанбе",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "МСШ №10",
                "address": "ш. Душанбе, кӯч. Алишер Навоӣ 4А (Пушти Барқи тоҷик)",
                "city": "Сино",
                "region": "Душанбе",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "МСШ №11",
                "address": "ш. Душанбе, кӯч. Панфилова (назди Беморхонаи пуст, Мясокомбинат)",
                "city": "Фирдавсӣ",
                "region": "Душанбе",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "МСШ №12",
                "address": "ш. Душанбе, кӯч. Деҳотӣ 50А (назди Диагностика)",
                "city": "Фирдавсӣ",
                "region": "Душанбе",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "МСШ №13",
                "address": "ш. Душанбе, кӯч. Бухоро 51 (назди Донишгоҳи Славянӣ)",
                "city": "Шоҳмансур",
                "region": "Душанбе",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "МСШ №14",
                "address": "ш. Душанбе, кӯч. Бобо Ҳамдамов 2/2 (Зарафшон)",
                "city": "Сино",
                "region": "Душанбе",
            },
            {
                "institution_type": "PRIMARY_CARE",
                "name": "МСШ №15",
                "address": "ш. Душанбе, кӯч. Неъмат Қарабоев 60 (назди МТ Истиқлол)",
                "city": "Фирдавсӣ",
                "region": "Душанбе",
            },
        ]

        medical_institutions = []
        for data in medical_institutions_data:
            region = Region.objects.get(name=data["region"])
            institution_type = MedicalInstitution.InstitutionType[data["institution_type"]] 
            city, created = City.objects.get_or_create(name=data["city"], region=region)
            institution = MedicalInstitution.objects.create(
                name=data["name"],
                institution_type=institution_type,
                address=data["address"],
                country="Таджикистан",
                region=region,
                city=city,
                phone_number='',
                email=fake.email(),
                website=fake.url(),
            )
            medical_institutions.append(institution)

        self.stdout.write(self.style.SUCCESS(f"Создано {len(medical_institutions)} медицинских учреждений."))

        self.stdout.write(self.style.SUCCESS("База данных успешно заполнена!"))