# Generated by Django 5.1.6 on 2025-04-25 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_time', models.DateTimeField(auto_now_add=True, help_text='Время, когда пациент пришёл на приём', verbose_name='Время визита')),
                ('diagnosis', models.TextField(blank=True, help_text='Заключение или диагноз, поставленный врачом', null=True, verbose_name='Диагноз')),
                ('prescriptions', models.TextField(blank=True, help_text='Назначения врача: лекарства, процедуры, рекомендации', null=True, verbose_name='Назначения')),
                ('status', models.CharField(choices=[('scheduled', 'Запланирован'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], default='scheduled', help_text='Статус визита', max_length=10, verbose_name='Статус визита')),
                ('notes', models.TextField(blank=True, help_text='Дополнительные примечания для визита', null=True, verbose_name='Примечания')),
                ('anamnesis', models.TextField(blank=True, help_text='Информация об анамнезе пациента (необязательное поле)', null=True, verbose_name='Анамнез')),
                ('appointment', models.OneToOneField(help_text='Запись пациента на приём (если визит был по записи)', on_delete=django.db.models.deletion.CASCADE, related_name='visit', to='appointments.appointment', verbose_name='Запись на приём')),
            ],
            options={
                'verbose_name': 'Посещение',
                'verbose_name_plural': 'Посещения',
            },
        ),
    ]
