# Generated by Django 5.1.6 on 2025-05-02 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_base', '0004_socialstatus'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='social_status',
            field=models.ForeignKey(blank=True, help_text='Социальный статус пациента.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_base.socialstatus', verbose_name='Социальный статус'),
        ),
        migrations.DeleteModel(
            name='SocialStatus',
        ),
    ]
