# Generated by Django 5.1.6 on 2025-04-25 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_base', '0004_academicdegree'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='academic_degree',
            field=models.ForeignKey(blank=True, help_text='Ученая степень врача (если есть)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_base.academicdegree', verbose_name='Ученая степень'),
        ),
        migrations.DeleteModel(
            name='AcademicDegree',
        ),
    ]
