# Generated by Django 5.1.6 on 2025-04-28 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_base', '0002_medicalcategory'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='medical_category',
            field=models.ForeignKey(blank=True, help_text='Категория врача (например, высшая, первая)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_base.medicalcategory', verbose_name='Медицинская категория'),
        ),
        migrations.DeleteModel(
            name='MedicalCategory',
        ),
    ]
