# Generated by Django 5.1.6 on 2025-04-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_base', '0002_specialty'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='specialty',
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialties',
            field=models.ManyToManyField(blank=True, help_text='Основные специализации врача', to='a_base.specialty', verbose_name='Специализации'),
        ),
        migrations.DeleteModel(
            name='Specialty',
        ),
    ]
