# Generated by Django 5.1.6 on 2025-05-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='about_ru',
            field=models.TextField(blank=True, help_text='Краткое описание своей деятельности', null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='about_tg',
            field=models.TextField(blank=True, help_text='Краткое описание своей деятельности', null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='philosophy_ru',
            field=models.TextField(blank=True, help_text='Краткое описание подхода к пациентам', null=True, verbose_name='Философия работы'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='philosophy_tg',
            field=models.TextField(blank=True, help_text='Краткое описание подхода к пациентам', null=True, verbose_name='Философия работы'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='titles_and_merits_ru',
            field=models.TextField(blank=True, help_text='Например: Отличник здравоохранения, член-корреспондент АМН', null=True, verbose_name='Звания и заслуги'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='titles_and_merits_tg',
            field=models.TextField(blank=True, help_text='Например: Отличник здравоохранения, член-корреспондент АМН', null=True, verbose_name='Звания и заслуги'),
        ),
    ]
