# Generated by Django 5.1.6 on 2025-04-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_base', '0003_serviceplace_service'),
        ('doctors', '0002_alter_doctor_medical_category_delete_medicalcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='services',
            field=models.ManyToManyField(blank=True, help_text='Медицинские услуги, которые предоставляет врач', to='a_base.service', verbose_name='Услуги'),
        ),
    ]
