# Generated by Django 5.1.6 on 2025-05-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_about_ru_doctor_about_tg_doctor_philosophy_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='city_ru',
            field=models.CharField(help_text='Город, где находится учебное заведение', max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='education',
            name='city_tg',
            field=models.CharField(help_text='Город, где находится учебное заведение', max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='education',
            name='country_ru',
            field=models.CharField(help_text='Страна, где находится учебное заведение', max_length=100, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='education',
            name='country_tg',
            field=models.CharField(help_text='Страна, где находится учебное заведение', max_length=100, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='education',
            name='institution_name_ru',
            field=models.CharField(help_text='Название учебного заведения', max_length=255, null=True, verbose_name='Название вуза'),
        ),
        migrations.AddField(
            model_name='education',
            name='institution_name_tg',
            field=models.CharField(help_text='Название учебного заведения', max_length=255, null=True, verbose_name='Название вуза'),
        ),
    ]
