# Generated by Django 5.1.6 on 2025-05-03 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_education_city_ru_education_city_tg_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Расписание рабочих часов', 'verbose_name_plural': 'Расписание рабочих часов'},
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='workplace',
        ),
        migrations.AddField(
            model_name='workplace',
            name='schedule',
            field=models.OneToOneField(blank=True, help_text='Расписание по дням недели по которому работает врач', null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.schedule', verbose_name='Расписание'),
        ),
    ]
